
export const lang = {
  startsWith: "Comienza con",
  contains: "Contiene",
  notContains: "No contiene",
  endsWith: "Termina con",
  equals: "Es igual a",
  notEquals: "No es igual",
  noFilter: "Sin filtro",
  lt: "Menos de",
  lte: "Menos de o igual a",
  gt: "Mayor que",
  gte: "Mayor o igual que",
  dateIs: "La fecha es",
  dateIsNot: "La fecha no es",
  dateBefore: "La fecha es anterior a",
  dateAfter: "La fecha es posterior a",
  clear: "Borrar",
  apply: "Aplicar",
  matchAll: "Combinar todo",
  matchAny: "Coincidir con cualquiera",
  addRule: "Añadir regla",
  removeRule: "Eliminar la regla",
  accept: "Sí",
  reject: "No",
  choose: "Elije",
  upload: "Subir a",
  cancel: "Cancelar",
  dayNames: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
  dayNamesShort: ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
  dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
  monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
  monthNamesShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
  today: "Hoy",
  weekHeader: "Sem",
  firstDayOfWeek: 0,
  dateFormat: "mm/dd/yy",
  weak: "Débil",
  medium: "Medio",
  strong: "Fuerte",
  passwordPrompt: "Escribe una contraseña",
  emptyFilterMessage: "No se han encontrado resultados",
  emptyMessage: "No hay opciones disponibles"
};
