export const es = {
  startsWith: "Comience con",
  contains: "Contenga",
  notContains: "No contenga",
  endsWith: "Termine con",
  equals: "Igual a",
  notEquals: "Diferente a",
  noFilter: "Sin filtro",
  lt: "Menor que",
  lte: "Menor o igual a",
  gt: "Mayor que",
  gte: "Mayor o igual a",
  dateIs: "Fecha igual a",
  dateIsNot: "Fecha diferente a",
  dateBefore: "Fecha antes de",
  dateAfter: "Fecha después de",
  custom: "Personalizar",
  clear: "Limpiar",
  apply: "Aplicar",
  matchAll: "Coincidir todo",
  matchAny: "Coincidir con cualquiera",
  addRule: "Agregar regla",
  removeRule: "Eliminar regla",
  accept: "Sí",
  reject: "No",
  choose: "Escoger",
  upload: "Subir",
  cancel: "Cancelar",
  dayNames: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
  dayNamesShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
  dayNamesMin: ["D", "L", "M", "X", "J", "V", "S"],
  monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
  monthNamesShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
  today: "Hoy",
  weekHeader: "Sem",
  firstDayOfWeek: 1,
  dateFormat: "dd/mm/yyyy",
  weak: "Débil",
  medium: "Medio",
  strong: "Fuerte",
  passwordPrompt: "Escriba una contraseña",
  emptyFilterMessage: "Sin opciones disponibles",
  emptyMessage: "No se han encontrado resultados",
  aria: {
    trueLabel: "Verdadero",
    falseLabel: "Falso",
    nullLabel: "No seleccionado",
    star: "1 estrella",
    stars: "{star} estrellas",
    selectAll: "Seleccionar todos",
    unselectAll: "Deseleccionar todos",
    close: "Cerrar",
    previous: "Anterior",
    next: "Siguiente",
    navigation: "Navegación",
    scrollTop: "Desplazarse arriba",
    moveTop: "Mover arriba",
    moveUp: "Subir",
    moveDown: "Bajar",
    moveBottom: "Desplazarse abajo",
    moveToTarget: "Mover al objectivo",
    moveToSource: "Mover al fuente",
    moveAllToTarget: "Mover todo al objetivo",
    moveAllToSource: "Mover todo al fuente",
    pageLabel: "{page}",
    firstPageLabel: "Primera Página",
    lastPageLabel: "Última Página",
    nextPageLabel: "Siguiente Página",
    previousPageLabel: "Página Anterior",
    rowsPerPageLabel: "Filas por página",
    jumpToPageDropdownLabel: "Ir al menú desplegable de página",
    jumpToPageInputLabel: "Ir a la entrada de página",
    selectRow: "Seleccionar fila",
    unselectRow: "Desmarcar fila",
    expandRow: "Expandir Fila",
    collapseRow: "Reducir Fila",
    showFilterMenu: "Mostrar menú del filtro",
    hideFilterMenu: "Ocultar menú del filtro",
    filterOperator: "Operador de filtro",
    filterConstraint: "Restricción de filtro",
    editRow: "Editar fila",
    saveEdit: "Guardar editado",
    cancelEdit: "Cancelar editado",
    listView: "Vista de lista",
    gridView: "Vista de cuadrícula",
    slide: "Deslizar",
    slideNumber: "{slideNumber}",
    zoomImage: "Ampliar imagen",
    zoomIn: "Ampliar",
    zoomOut: "Reducir",
    rotateRight: "Girar derecha",
    rotateLeft: "Girar izquierda"
  }
};

export const en = {
  startsWith: "Starts with",
  contains: "Contains",
  notContains: "Not contains",
  endsWith: "Ends with",
  equals: "Equals",
  notEquals: "Not equals",
  noFilter: "No Filter",
  filter: "Filter",
  lt: "Less than",
  lte: "Less than or equal to",
  gt: "Greater than",
  gte: "Greater than or equal to",
  dateIs: "Date is",
  dateIsNot: "Date is not",
  dateBefore: "Date is before",
  dateAfter: "Date is after",
  custom: "Custom",
  clear: "Clear",
  apply: "Apply",
  matchAll: "Match All",
  matchAny: "Match Any",
  addRule: "Add Rule",
  removeRule: "Remove Rule",
  accept: "Yes",
  reject: "No",
  choose: "Choose",
  upload: "Upload",
  cancel: "Cancel",
  completed: "Completed",
  pending: "Pending",
  dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  dayNamesShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  dayNamesMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
  monthNames: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  monthNamesShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  chooseYear: "Choose Year",
  chooseMonth: "Choose Month",
  chooseDate: "Choose Date",
  prevDecade: "Previous Decade",
  nextDecade: "Next Decade",
  prevYear: "Previous Year",
  nextYear: "Next Year",
  prevMonth: "Previous Month",
  nextMonth: "Next Month",
  prevHour: "Previous Hour",
  nextHour: "Next Hour",
  prevMinute: "Previous Minute",
  nextMinute: "Next Minute",
  prevSecond: "Previous Second",
  nextSecond: "Next Second",
  am: "am",
  pm: "pm",
  today: "Today",
  weekHeader: "Wk",
  firstDayOfWeek: 0,
  dateFormat: "mm/dd/yy",
  weak: "Weak",
  medium: "Medium",
  strong: "Strong",
  passwordPrompt: "Enter a password",
  emptyFilterMessage: "No results found",
  searchMessage: "{0} results are available",
  selectionMessage: "{0} items selected",
  emptySelectionMessage: "No selected item",
  emptySearchMessage: "No results found",
  emptyMessage: "No available options",
  aria: {
    trueLabel: "True",
    falseLabel: "False",
    nullLabel: "Not Selected",
    star: "1 star",
    stars: "{star} stars",
    selectAll: "All items selected",
    unselectAll: "All items unselected",
    close: "Close",
    previous: "Previous",
    next: "Next",
    navigation: "Navigation",
    scrollTop: "Scroll Top",
    moveTop: "Move Top",
    moveUp: "Move Up",
    moveDown: "Move Down",
    moveBottom: "Move Bottom",
    moveToTarget: "Move to Target",
    moveToSource: "Move to Source",
    moveAllToTarget: "Move All to Target",
    moveAllToSource: "Move All to Source",
    pageLabel: "{page}",
    firstPageLabel: "First Page",
    lastPageLabel: "Last Page",
    nextPageLabel: "Next Page",
    previousPageLabel: "Previous Page",
    rowsPerPageLabel: "Rows per page",
    jumpToPageDropdownLabel: "Jump to Page Dropdown",
    jumpToPageInputLabel: "Jump to Page Input",
    selectRow: "Row Selected",
    unselectRow: "Row Unselected",
    expandRow: "Row Expanded",
    collapseRow: "Row Collapsed",
    showFilterMenu: "Show Filter Menu",
    hideFilterMenu: "Hide Filter Menu",
    filterOperator: "Filter Operator",
    filterConstraint: "Filter Constraint",
    editRow: "Row Edit",
    saveEdit: "Save Edit",
    cancelEdit: "Cancel Edit",
    listView: "List View",
    gridView: "Grid View",
    slide: "Slide",
    slideNumber: "{slideNumber}",
    zoomImage: "Zoom Image",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    rotateRight: "Rotate Right",
    rotateLeft: "Rotate Left"
  }
};
